In [2]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [4]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [5]:
x.shape

torch.Size([2, 5])

In [7]:
y = torch.rand([2,5])
y

tensor([[0.8747, 0.0306, 0.9826, 0.6844, 0.8052],
        [0.9425, 0.0411, 0.8894, 0.8861, 0.7833]])

In [8]:
#Flattening operation: Same as reshape on Tensorflow
y.view([1,10])

tensor([[0.8747, 0.0306, 0.9826, 0.6844, 0.8052, 0.9425, 0.0411, 0.8894, 0.8861,
         0.7833]])

In [9]:
#Remember view method is pass by value, not reference
y

tensor([[0.8747, 0.0306, 0.9826, 0.6844, 0.8052],
        [0.9425, 0.0411, 0.8894, 0.8861, 0.7833]])

In [11]:
y = y.view([1,10]) #Show me the view of y as [1,10]
y

tensor([[0.8747, 0.0306, 0.9826, 0.6844, 0.8052, 0.9425, 0.0411, 0.8894, 0.8861,
         0.7833]])

In [12]:
y.shape

torch.Size([1, 10])